### ISSUE TITLE
Investigate: Issues setting up adamctl on Windows

### ISSUE THREAD

**Issue by carise** [B612-Asteroid-Institute/adam_home#98]
This is when a user tries to set up adamctl without WSL (which I am guessing is the preferred way to use adamctl)

**Comment by EmmieKing** [comment]
Kevin opened an Anaconda Prompt and installed with: “conda install -c asteroid-institute adam”

No problems

Kevin was not able to execute “adamctl login”. 'adamctl' not recognized.

We had to find the adamctl file location in order to execute the command: navigate to C:\Users\journ\Anaconda3\pkgs\adam-0.0.0.dev403+42ec1a2-py_0\python-scripts

Make sure you are using a Google account.

Initially, Kevin wanted to use Kevin@yogalola.com but could not retrieve a token.

John created a workspace ID for this account but it will not be used.

Switched email to journeybeyondthemat@gmail.com and was able to retrieve a token.

Carise gave me his workspace ID in our Slack channel.

Copy and Paste the token (user will not see the token in the prompt window)

The token was not accepted.

We found that .config/adam/config was not populated. Carise gave Kevin the correct format and information to paste and save into config.

envs:
 prod:
 token: …
 url: https://pro-equinox-162418.appspot.com/_ah/api/adam/v1
 workspace: …

no {} around info

no file extension when saved

<user home>/.config/adam/config

python adamctl config (to test if it worked)

Execute this command: adamctl config envs.prod.workspace "uuid-received-from-carise"

Worked!

Execute “jupyter notebook” from C:/User/Journ/Adam_home.

Navigate to ‘demos’ folder and execute ‘single_run_demo.ipynb’

Worked!

**Comment by carise** [comment]
I'm not sure why adamctl was putting an empty json in the config file. Couldn't reproduce that issue.

The copy-paste issue is probably an artifact of the underlying Windows command prompt. Ctrl-V by default won't copy stuff into a password-like prompt, which the Token prompt is. To get around that, set up copy-paste as per these instructions: https://stackoverflow.com/questions/52154271/how-do-i-copy-paste-in-anaconda-prompt

Then using crl-shift-v should allow pasting of the token.

Otherwise, a shorter way to get around these issues is to create file named "config" (no extension) in the user's home directory (usually: C:\Users\[username]\), in the path .config\adam.

The config file should contain some yaml, similar to the following:

```
envs:
  some_environment_name:
    token: YOUR_TOKEN_HERE
    url: ADAM_SERVER_URL
    workspace: YOUR_WORKSPACE_ID
```

**Comment by mjuric** [comment]
Interesting -- we never decided if we're supporting native windows as a platform (I assumed we weren't). If we are, let's upgrade the CI to test on Windows as well. Supporting it will cause special-casing of code that depends on well-known locations in the file system (e.g. storing of config files and similar). Not sure about other differences, it's been awhile since I worked on Win.

**Comment by carise** [comment]
Before we start writing code to address the Windows setup, I am wondering: would it be fine for us to just require that people using Windows set up WSL in order to use ADAM from Jupyter?

**Comment by EmmieKing** [comment]
I'm not familiar with WSL. How do tokens get passed to ADAM from WSL? Do will still need the config?

**Comment by carise** [comment]
[WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) is a compatibility layer for running Linux binaries natively in Windows 10, so in theory, you would be able to run the adamctl setup instructions from the README directly without special workarounds (which we had to do for Powershell).

The token would still be pasted into the command prompt, and the config should be automatically created in whatever the home directory is under WSL.

**Comment by carise** [comment]
Upate:

* The issue with the {} and having to manually create a config file can be fixed by providing a default dict, {'envs': {}} when the config file path cannot be found using.
* adamctl CLI utility not being directly accessible in Powershell. The conda recipe needs to include the console script entry point.

See #134
